on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'COPYING'
      - 'website/**'
      - '.github/*.md'
      - '.github/FUNDING.yml'

name: Build Code
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - name: Checkout code ðŸ‘‹
      uses: actions/setup-node@v4.2.0
    - name: Install Go ðŸ—³
      uses: ./.github/workflows/composite/bootstrap-go
    - name: Run GoReleaser ðŸš€
      uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200
      with:
        distribution: goreleaser
        version: latest
        args: build --clean --snapshot --skip=post-hooks --skip=before
        workdir: src
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: builds
        retention-days: 1
        path: |
          src/dist
